---
k3s_version: v1.31.5+k3s1
ansible_user: ubuntu
kube_vip_address: "192.168.2.6"
network_interface: "enp0s1"

# GitHub Runner Configuration
github_repo_url: "https://github.com/YOUR_USER/k3s-services-deploy"
github_runner_token: "NONE"
