---
k3s_version: v1.31.5+k3s1
ansible_user: ubuntu
kube_vip_address: "192.168.2.6"
network_interface: "enp0s1"
cluster_cidr: "10.244.0.0/16"
service_cidr: "10.96.0.0/16"
k3s_domain: "k3s-multipass.local"

# GitHub Runner Configuration
github_repo_url: "https://github.com/YOUR_USER/k3s-services-deploy"
github_runner_token: "NONE"
