---
- name: "Verify connectivity"
  ansible.builtin.ping:

- name: "Install dependencies"
  ansible.builtin.apt:
    update_cache: true
    name:
      - curl
      - ca-certificates
      - gnupg
      - nfs-common
    state: present

- name: "Disable Swap"
  ansible.builtin.command: swapoff -a
  when: ansible_facts['swaptotal_mb'] > 0
  changed_when: true

- name: "Remove Swap from fstab"
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+.*)$'
    replace: '# \1'
